name: Test

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      project:
        required: false
        type: string
      nuget_feed:
        required: false
        type: string
      nuget_username:
        required: false
        type: string
      pack:
        required: false
        type: string
        default: false
    secrets:
      nuget_password:
        required: false

jobs:

  build:
    name: Build
    runs-on: ${{ inputs.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_CERT_REVOCATION_MODE: offline
      DOTNET_NUGET_SIGNATURE_VERIFICATION: false
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Add NuGet Source
      if: ${{ inputs.nuget_feed != '' }}
      shell: bash
      run: >
        dotnet nuget add source
        --username "${{ inputs.nuget_username }}"
        --password "${{ secrets.nuget_password }}"
        --store-password-in-clear-text
        "${{ inputs.nuget_feed }}"

    - name: Restore NuGet Dependencies
      run: >
        dotnet restore "${{ inputs.project }}"
        --nologo
        --verbosity minimal

    - name: Build
      run: >
        dotnet build "${{ inputs.project }}"
        --configuration "Release"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        -p:SurveyorFeed="${{ inputs.nuget_feed }}"
        -p:SurveyorToken="${{ secrets.nuget_password }}"
        --nologo
        --no-restore
        --verbosity minimal

    - name: Test
      run: >
        dotnet test "${{ inputs.project }}"
        --configuration "Release"
        --nologo
        --no-build
        --verbosity quiet
        --logger="Console;verbosity=normal"
        --logger html
        --logger trx
        --results-directory artifacts/tests

    - name: List Test Results
      if: ${{ always() }}
      continue-on-error: true
      run: ls -R1 artifacts/tests

    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Tests-${{ runner.os }}-${{ runner.arch }}
        path: artifacts/tests

    - name: Pack
      if: ${{ inputs.pack == 'true' }}
      run: >
        dotnet pack "${{ inputs.project }}"
        --configuration "Release"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        -p:SurveyorFeed="${{ inputs.nuget_feed }}"
        -p:SurveyorToken="${{ secrets.nuget_password }}"
        --no-build
        --output artifacts/packages

    - name: List Packages
      if: ${{ inputs.pack == 'true' }}
      continue-on-error: true
      run: ls -R1 artifacts/packages

    - name: Upload Packages
      if: ${{ inputs.pack == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: artifacts
