name: Push

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      project:
        required: false
        type: string
      nuget_feed:
        required: false
        type: string
      nuget_username:
        required: false
        type: string
    secrets:
      nuget_password:
        required: false

jobs:

  push:
    name: Push
    runs-on: ${{ inputs.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_CERT_REVOCATION_MODE: offline
      DOTNET_NUGET_SIGNATURE_VERIFICATION: false
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Add NuGet Source
      if: ${{ inputs.nuget_feed != '' }}
      shell: bash
      run: >
        dotnet nuget add source
        --username "${{ inputs.nuget_username }}"
        --password "${{ secrets.nuget_password }}"
        --store-password-in-clear-text
        "${{ inputs.nuget_feed }}"

    - name: Restore NuGet Dependencies
      run: >
        dotnet restore "${{ inputs.project }}"
        --nologo
        --verbosity minimal

    - name: Build
      run: >
        dotnet build "${{ inputs.project }}"
        --configuration "Release"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        --nologo
        --no-restore
        --verbosity minimal

    - name: Pack
      run: >
        dotnet pack "${{ inputs.project }}"
        --configuration "Release"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        --no-build
        --output artifacts

    - name: List Artifacts
      run: ls -1 artifacts

    - name: Push To GitHub Packages
      run: >
        dotnet nuget push "artifacts/*"
        --skip-duplicate
        --source "https://nuget.pkg.github.com/StudioLE/index.json"
        --symbol-source "https://nuget.pkg.github.com/StudioLE/index.json"
        --api-key "${{ secrets.GITHUB_TOKEN }}"
