name: CI/CD

on:
  push:

jobs:

  test-ubuntu:
    name: Ubuntu
    uses: ./01-test.yml
    with:
      project: ""
      os: ubuntu-latest
    secrets: inherit

  test-windows:
    name: Windows
    environment: Production
    uses: ./.github/workflows/01-test.yml
    with:
      project: ""
      os: windows-latest
    secrets: inherit

  release:
    name: Release
    environment: Production
    needs:
      - test-ubuntu
    uses: ./.github/workflows/02-release.yml
    secrets: inherit

  push:
    name: Push NuGet
    environment: Production
    needs:
      - release
    uses: ./.github/workflows/03-push.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
