name: CI/CD

on:
  push:

jobs:

  test-ubuntu:
    name: Ubuntu
    uses: ./01-test.yml
    with:
      project: ""
      os: ubuntu-latest
    secrets: inherit

  test-windows:
    name: Windows
    environment: Production
    uses: ./01-test.yml
    with:
      project: ""
      os: windows-latest
    secrets: inherit

  release:
    name: Release
    environment: Production
    needs:
      - test-ubuntu
    uses: ./02-release.yml
    secrets: inherit

  publish-nuget:
    name: Publish NuGet
    environment: Production
    needs:
      - release
      - build-and-test-ubuntu
    uses: StudioLE/Actions/.github/workflows/03-publish-nuget.yml@main
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
