name: CI/CD

on:
  push:

jobs:

  test-ubuntu:
    name: Ubuntu
    uses: ./.github/workflows/01-test.yml
    with:
      project: ""
      os: ubuntu-latest
    secrets: inherit

  test-windows:
    name: Windows
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    uses: ./.github/workflows/01-test.yml
    with:
      project: ""
      os: windows-latest
    secrets: inherit

  release:
    name: Release
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - test-ubuntu
    uses: ./.github/workflows/02-release.yml
    secrets: inherit

  push:
    name: Push
    needs:
      - release
    uses: ./.github/workflows/03-push.yml
    with:
      project: ""
      version: ${{ needs.release.outputs.version }}
      environment: ${{ needs.release.outputs.environment }}
    secrets: inherit
