name: CI/CD

on:
  push:

jobs:

  test-ubuntu:
    name: Ubuntu
    uses: ./.github/workflows/01-test.yml
    with:
      project: ""
      os: ubuntu-latest
    secrets: inherit

  production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo "Hello, world!"

  test-windows:
    name: Windows
    uses: ./.github/workflows/01-test.yml
    needs:
      - production
    with:
      project: ""
      os: windows-latest
    secrets: inherit

  release:
    name: Release
    needs:
      - production
      - test-ubuntu
    uses: ./.github/workflows/02-release.yml
    secrets: inherit

  push:
    name: Push NuGet
    needs:
      - release
    uses: ./.github/workflows/03-push.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
