name: CI/CD

on:
  push:

jobs:

  release:
    name: Create Release
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit

  build-and-test-ubuntu:
    name: Ubuntu
    needs: release
    uses: StudioLE/Actions/.github/workflows/02-build-and-test.yml@main
    with:
      solution: ""
      os: ubuntu-latest
      version: ${{ needs.release.outputs.version }}
    secrets: inherit

  build-and-test-windows:
    name: Windows
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs: release
    uses: StudioLE/Actions/.github/workflows/02-build-and-test.yml@main
    with:
      solution:  ""
      os: windows-latest
      version: ${{ needs.release.outputs.version }}
    secrets: inherit

  publish-nuget:
    name: Publish NuGet
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - release
      - build-and-test-ubuntu
    uses: StudioLE/Actions/.github/workflows/03-publish-nuget.yml@main
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
