name: Docker Push
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      registry:
        required: false
        type: string
        default: ghcr.io
      user:
        required: false
        type: string
        default: ${{ github.actor.toLower() }}
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: false
        type: string
    secrets:
      password:
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}
jobs:

  docker-push:
    runs-on: ${{ inputs.os }}
    steps:

    - name: Login
      run: echo "$PW" | docker login ${{ inputs.registry }} -u ${{ inputs.user }} --password-stdin
      env:
        PW: ${{ inputs.password }}

    - name: Pull
      run: >
        docker pull
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ github.sha }}

    - name: Tag version
      run: >
        docker tag
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ github.sha }}
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ inputs.version }}

    - name: Push version
      run: >
        docker push
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ inputs.version }}

    - name: Tag
      if: inputs.tag != ''
      run: >
        docker tag
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ github.sha }}
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ inputs.tag }}

    - name: Push
      if: inputs.tag != ''
      run: >
        docker push
        ${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}:${{ inputs.tag }}
