name: Docker Build
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      name:
        required: true
        type: string
      args:
        required: false
        type: string
jobs:

  docker-build:
    runs-on: ${{ inputs.os }}
    steps:

    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ github.sha }}
        restore-keys: |
          buildx-

    - name: Login
      run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create
      run: docker buildx create --use

    - name: Build
      run: >
        docker buildx build .
        --tag ghcr.io/${{ github.actor }}/${{ inputs.name }}:${{ github.sha }}
        --cache-from=type=local,src=/tmp/.buildx-cache
        --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max
        --push
        ${{ inputs.args }}

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - run: rm -rf /tmp/.buildx-cache
    - run: mv /tmp/.buildx-cache-new /tmp/.buildx-cache
