name: Publish

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      runtime:
        required: true
        type: string
      npm:
        required: false
        type: string
      workload:
        required: false
        type: string
      name:
        required: true
        type: string
      path:
        required: false
        default: ""
        type: string
      version:
        required: true
        type: string
      nuget_feed:
        required: false
        type: string
      nuget_username:
        required: false
        type: string
    secrets:
      nuget_password:
        required: false

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_CERT_REVOCATION_MODE: offline
      DOTNET_NUGET_SIGNATURE_VERIFICATION: false
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Restore npm Dependencies
      if: ${{ inputs.npm != '' }}
      working-directory: ${{ inputs.npm }}
      run: |
        npm install
        npm run build

    - name: Install workload
      if: ${{ inputs.workload != '' }}
      run: dotnet workload install ${{ inputs.workload }}

    - name: Add NuGet Source
      if: ${{ inputs.nuget_feed != '' }}
      shell: bash
      run: >
        dotnet nuget add source
        --username "${{ inputs.nuget_username }}"
        --password "${{ secrets.nuget_password }}"
        --store-password-in-clear-text
        "${{ inputs.nuget_feed }}"

    - name: Publish
      run: >
        dotnet publish "${{ inputs.project }}"
        -p:SurveyorFeed="${{ inputs.nuget_feed }}"
        -p:SurveyorToken="${{ secrets.nuget_password }}"
        --configuration "Release"
        --runtime "${{ inputs.runtime }}"
        --output artifacts

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: artifacts/${{ inputs.path }}

    - name: Upload Release Asset
      if: ${{ inputs.version != '' }}
      working-directory: artifacts/${{ inputs.path }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        zip -r -9 "${{ inputs.name }}.zip" *
        gh release upload "v${{ inputs.version }}" "${{ inputs.name }}.zip" --clobber
